name: Flutter Ultra-Min Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Wipe all dependencies except flutter
        run: |
          grep -E "name:|description:|version:|environment:" pubspec.yaml > pubspec_min.yaml
          echo "dependencies:" >> pubspec_min.yaml
          echo "  flutter:" >> pubspec_min.yaml
          echo "    sdk: flutter" >> pubspec_min.yaml
          mv pubspec_min.yaml pubspec.yaml

      - run: flutter pub get

      - name: Full Android rebuild
        run: |
          rm -rf android
          flutter create --project-name bpb_jahani70 .
          sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/' android/app/build.gradle

      - run: flutter clean
      - run: flutter build apk --release -v

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
