name: Flutter Ultra-Clean Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Remove Android-heavy plugins from pubspec
        run: |
          cp pubspec.yaml pubspec_backup.yaml
          grep -v -E "firebase|google_sign_in|flutter_local_notifications|path_provider_android|shared_preferences_android" pubspec.yaml > temp.yaml
          mv temp.yaml pubspec.yaml

      - run: flutter pub get

      - name: Full Android rebuild
        run: |
          rm -rf android
          flutter create .
          sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/' android/app/build.gradle

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release -v

      - uses: actions/upload-artifact@v4
