name: Flutter Build APK (No Google Services)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      ##########################################################
      # حذفی کامل google-services از تمامی فایل‌ها
      ##########################################################
      - name: Disable ALL google-services refs
        run: |
          echo "Searching for any reference to google-services in project..."
          MATCHES=$(grep -R "google-services" . || true)
          if [ -n "$MATCHES" ]; then
            echo "Found google-services references:"
            echo "$MATCHES"
            echo "Commenting out google-services in all gradle files..."
            grep -Rl "google-services" . | grep "\.gradle" | while read f; do
              echo "Processing $f"
              cp "$f" "$f.ci_backup"
              sed -i "s@apply plugin: 'com.google.gms.google-services'@//apply plugin: 'com.google.gms.google-services'@g" "$f" || true
              sed -i "s@classpath 'com.google.gms:google-services:[^']*'@//classpath 'com.google.gms:google-services'@g" "$f" || true
            done
          else
            echo "No google-services reference found."
          fi

      ##########################################################
      # Build APK
      ##########################################################
      - name: Build APK (verbose)
        run: |
          flutter clean
          flutter pub get --verbose
          flutter build apk --release -v

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
