name: Flutter Auto-Rebuild & Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get || true

      ##########################################################
      # ساخت پروژه جدید با قالب آپدیت و انتقال کدها
      ##########################################################
      - name: Rebuild Android project if unsupported
        run: |
          echo "Checking android project..."
          if ! [ -f "android/build.gradle" ]; then
            echo "⚠️ Android project missing, recreating..."
            flutter create -t app temp_new_app
            # انتقال کدها
            rm -rf temp_new_app/lib
            cp -r lib temp_new_app/lib
            cp pubspec.yaml temp_new_app/pubspec.yaml
            if [ -d "assets" ]; then
              cp -r assets temp_new_app/assets
            fi
            # جایگزینی پروژه
            rm -rf android
            mv temp_new_app/android android
            rm -rf temp_new_app
          else
            if grep -q "Unsupported Gradle project" android/build.gradle; then
              echo "⚠️ Detected unsupported Gradle project, recreating..."
              flutter create -t app temp_new_app
              rm -rf temp_new_app/lib
              cp -r lib temp_new_app/lib
              cp pubspec.yaml temp_new_app/pubspec.yaml
              if [ -d "assets" ]; then
                cp -r assets temp_new_app/assets
              fi
              rm -rf android
              mv temp_new_app/android android
              rm -rf temp_new_app
            else
              echo "✅ Android project seems fine."
            fi
          fi

      ##########################################################
      # Build APK Release
      ##########################################################
      - name: Build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release -v

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
