name: Flutter Safe-Rebuild & Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - run: flutter pub get || true

      - name: Rebuild Android Project (Safe Mode)
        run: |
          echo "♻ Removing old android folder..."
          rm -rf android
          echo "📦 Creating new android project..."
          flutter create -t app temp_new_app
          rm -rf temp_new_app/lib
          cp -r lib temp_new_app/lib
          cp pubspec.yaml temp_new_app/pubspec.yaml
          if [ -d "assets" ]; then
            cp -r assets temp_new_app/assets
          fi
          mv temp_new_app/android android
          rm -rf temp_new_app
          
          echo "🛠 Adjusting Gradle settings..."
          # Set Gradle & AGP versions
          sed -i 's/com.android.application.*/com.android.application version "8.1.0"/' android/build.gradle || true
          sed -i 's/kotlin("android").*/id("org.jetbrains.kotlin.android") version "1.8.22"/' android/build.gradle || true
          
          # Remove google-services plugin if present
          sed -i '/com.google.gms.google-services/d' android/app/build.gradle || true

          # Ensure minSdkVersion is at least 21
          sed -i 's/minSdkVersion [0-9]\+/minSdkVersion 21/' android/app/build.gradle

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release -v

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
